/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Student = IDL.Record({
  'id' : IDL.Nat,
  'pin' : IDL.Nat,
  'fees' : IDL.Vec(IDL.Bool),
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  'createStudent' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'getAllFees' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(IDL.Bool)))],
      ['query'],
    ),
  'getStudent' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
  'getStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'loginStudent' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], ['query']),
  'markFeePaid' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'pin' : IDL.Nat,
    'fees' : IDL.Vec(IDL.Bool),
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    'createStudent' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'getAllFees' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(IDL.Bool)))],
        ['query'],
      ),
    'getStudent' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
    'getStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'loginStudent' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], ['query']),
    'markFeePaid' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };